### ISSUE TITLE
Melden eines nicht existenten Bahnhofs

### ISSUE THREAD

**Issue by khgdrn** [RailwayStations/RSAndroidApp#104]
z.B. über einen weiteren Knopf in den Bahnhofs-Details unten neben der Kamera oder Galerieauswahl. 
Wie der Prozess dann läuft kann ganz unterschiedlich sein, ich beschreibe mal, wie ich das heute mache.
Ein User meldet über Twitter einen Geisterbahnhof.
Ich lade ein Geisterbahnhofs-Foto hoch.
Das nächste mal im Download sehe ich dieses Foto und habe die ID.
Mit der ID suche in elasticsearch die ID dort.
Logge mich per Putty ein und setze den Löschbefehl.
Am Beispiel Achern Stadt. Hat die 8040102. 
http://94.136.168.53/bahnhoefe/_search?q=BahnhofNr=8040102
hat die _id":"AV7906VlRqXmo6ccrnio
Löschbefehl: curl -XDELETE localhost:9200/bahnhoefe/bahnhof/AV7906VlRqXmo6ccrnio

Wenn im ersten Schritt ein Standardbild verschickt wird, würde das in jedem Fall schonmal helfen. z.B. das hier: https://pixabay.com/de/prellbock-bremsprellbock-lost-places-3310947/

**Comment by khgdrn** [comment]
allein der Titel ist schon nicht eindeutig. Also, es geht um den Fall: Wir haben einen Bahnhof in der Datenbasis. Vor Ort gibt es aber keinen und das will ich melden.

**Comment by pstorch** [comment]
So in der Art, als dritte Möglichkeit im Detailscreen?

![screenshot_railway_station_photos_20180930-214858](https://user-images.githubusercontent.com/5598124/46261962-2caa6500-c4fb-11e8-9aad-95605607f556.png)

Wenn wir es im Menü verstecken sieht und nutzt es keiner, denke ich.

**Comment by khgdrn** [comment]
yes :+1:
