### ISSUE TITLE
`few` and `many` quantities of polish translations for `stations_loaded` and `records_found`

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#119]
AndroidStudio complained that polish translation need the `few` and `many` quantities. I just copied the `other` quantity:

https://github.com/RailwayStations/RSAndroidApp/blob/42023f860e4b0c0e67a6e5cc4920e572a6f4104c/app/src/main/res/values-pl/strings.xml#L186

https://github.com/RailwayStations/RSAndroidApp/blob/42023f860e4b0c0e67a6e5cc4920e572a6f4104c/app/src/main/res/values-pl/strings.xml#L192

Maybe @jankowiakmaria or @kubatyszko can once again help here?

**Comment by kniziol** [comment]
Hi @pstorch. Could you, please, define the numerical intervals that you would like to use with each translation?

Examples:
- `few` - `2 - 5`
- `many` - `6 - 10`
- `other` - `10 - infinity`

It will facilitate making the translations.

**Comment by pstorch** [comment]
Hi @kniziol, thanks for your help. We don't set a range in our application, but Android defines them like this:

![image](https://user-images.githubusercontent.com/5598124/64485253-95778280-d21e-11e9-845e-61a9c55f443d.png)

Does it help to do the right translation?

**Comment by kniziol** [comment]
@pstorch thank you. I will prepare the PR.

**Comment by pstorch** [comment]
outdated
