### ISSUE TITLE
Read 'active' flag from stations

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#134]
Read the `active` flag from the stations and show it (e.g. greyed out marker on the map).
Optionally add a filter for the user to show only active stations.

**Comment by kaiwinter** [comment]
I could build this. Do you prefer one icon for all three states (with photo, without photo, with own photo) of a station or three different icons (maybe versions of the current three which are half colored and half grey)?

A filter doesn't fit very well I think as the current filter (the toolbar icon which toggles four states) isn't very self explaining and a fifth (or even more) state may harm the usability even more.

**Comment by pstorch** [comment]
Yes, you are right. The filter and icon combinations will grow too complicated.
Maybe as first step we should just show it on the details page, that this station is inactive.

**Comment by kaiwinter** [comment]
How do you like these icons?
![all](https://user-images.githubusercontent.com/110982/65816510-e87c9e00-e1fc-11e9-980c-1a8acdd89cba.png) 
or these: 
![all2](https://user-images.githubusercontent.com/110982/65817143-08fc2680-e204-11e9-975a-ea7b8d95a2f9.png)
We can show them for inactive stations but don't make them filterable. Or would you rather keep the same icons for active and inactive stations?

**Comment by pstorch** [comment]
I like the first ones (half gray). 👍
