### ISSUE TITLE
Bitmap.incrementRefCount called on wrong object

### ISSUE THREAD

**Issue by kaiwinter** [RailwayStations/RSAndroidApp#135]
`Bitmap.incrementRefCount` is called on `markerWithoutPhoto` but from the context it should be called on `markerOwnPhoto`. I just can guess the implication (I don't see any Javadoc), but I think this should be fixed.

See https://github.com/RailwayStations/RSAndroidApp/blob/540c70de8be571cf340a7cb2108fd28b9838aa1b/app/src/main/java/de/bahnhoefe/deutschlands/bahnhofsfotos/MapsActivity.java#L553

**Comment by pstorch** [comment]
Yes, you are right. It's probably a Copy & Paste error.

**Comment by pstorch** [comment]
@kaiwinter do you want to fix it while on #134 ? Otherwise I could also fix it.

**Comment by kaiwinter** [comment]
Yes that was my intention. This issue was meant to be for documentation purpose... I'm working on that code fragment in #134
