### ISSUE TITLE
Zurück sollte zur vorherigen Ansicht führen, nicht immer die Bahnhofsliste

### ISSUE THREAD

**Issue by pief** [RailwayStations/RSAndroidApp#148]
Wenn man auf der Bahnhofskarte ist und sich einen Bahnhof anschaut und dann auf Zurück geht, landet man auf der Bahnhofsliste statt der -karte und muss erst wieder umständlich "Bahnhofskarte" auswählen. Der Zurück-Knopf sollte hier so funktionieren wie erwartet, nämlich sich merken was die vorherige Ansicht war und dorthin zurück springen.

**Comment by pstorch** [comment]
Kann ich bestätigen. Das ist leider im letzten Update kaputt gegangen.
