### ISSUE TITLE
Status "Foto hochgeladen aber in Prüfung" visualisieren

### ISSUE THREAD

**Issue by pief** [RailwayStations/RSAndroidApp#149]
Ich fände es toll, wenn man sehen könnte, dass man a.) für einen Bahnhof bereits erfolgreich ein Foto hochgeladen hat (think Serverprobleme, Netzprobleme) und b.) dieses noch in Prüfung ist, also nicht abgelehnt und damit gelöscht wurde. Hierzu würde ich vorschlagen:
1. auf der Bahnhofsansicht eine Zeile einblenden ("Hochgeladen am mm.dd.yyyy HH:MM:SS")
2. auf der Bahnhofskarte eine weitere Farbe vorsehen (z.B. Gelb statt Rot)

**Comment by pstorch** [comment]
Ja, daran habe ich auch schon gedacht. Das ist eine gute Idee
