### ISSUE TITLE
Nutzen Funktion "Eigene Fotos" / Abgleich mit Server

### ISSUE THREAD

**Issue by pief** [RailwayStations/RSAndroidApp#150]
Mir ist der Nutzen der Funktion "Eigene Fotos" nicht ganz klar. Ich sehe hier ja wenn ich es richtig erfasse sämtliche Uplaods, die ich jemals gemacht habe, auch wenn ich z.B. selbst nachträglich ein anderes Foto für einen Bahnhof hochgeladen habe oder ein Foto abgelehnt wurde, oder? Wenn dies so ist, wäre dann nicht ein Abgleich mit dem Server sinnvoll, so dass ich nur auch wirklich aktive Fotos sehe?

**Comment by pstorch** [comment]
Die Funktion ist nicht  selbsterklärend. Im Moment werden dort alle Fotos gelistet, die du über die App gemacht hast. Ein Abgleich findet bisher nicht statt.

Es wird zum Teil genutzt, um tagsüber auf Tour zu gehen und dann abends im WLAN die Ausbeute zu sichten und hochzuladen. 

Wie wäre dein Verständnis von dieser Funktion?

**Comment by pief** [comment]
Ich hatte eben gar keins :)

Wenn es um einen Zwischenspeicher zum Upload geht, hätte ich eine entsprechende Benennung "Deine Foto-Warteschlange" und einen Abgleich erwartet. Ansonsten, "Deine Fotos" geht ja im Prinzip über das Icon oben rechts links vom "..."-Icon.

**Comment by pstorch** [comment]
`Foto-Warteschlange` ist auch ein guter Begriff. Wir hatten ein bisschen nach einem passenden Begriff gesucht. `In Bearbeitung` war zuletzt unser Favorit.
