### ISSUE TITLE
Timeout bei Netzausfall führt zu verwirrenden Paketen im Eingangskorb

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#162]
Auf Grund von
Verbindungsproblemen kommt die Meldung, dass das Bild nicht hochgeladen
werden kann (Timeout) und dann bei jeden weiteren Versuch ein Paket im
Eingangskorb liegt, von dem ich nicht weiss, ob das Bild doch mit
hochgeladen wurde?

**Comment by pstorch** [comment]
Ich kann das in der aktuellen Version nicht nachvollziehen.
