### ISSUE TITLE
Introslider

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#22]
1. Wofür ist die App überhaupt da
2. Was ist "In der Nähe"
3. Was sind "alle fehlenden Bahnhöfe"
4. Hochladen nicht möglich, da Qualitätskontrolle notwendig - Versand per Mail
5. Teilen-Button erklären
6. Hinweis "Meine Daten ausfüllen" (unbedingt als Letztes, da es in Erinnerung bleiben soll)

**Comment by tursics** [comment]
1. gleich mit einem Beispielbild eines bereits fotografierten (schönen) Bahnhofs

**Comment by androidoma** [comment]
Done
