### ISSUE TITLE
Änderung der Icons

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#23]
Mit Hilfe von @tursics

**Comment by tursics** [comment]
Ja. Das mache ich gerne. Lass uns mal sammeln:

- App-Icon sollte keine durchsichtige Innenfläche haben
- "Meine Daten" ein Profil-Mensch-Icon
- "Deine Fotos" das Kamera-Icon
- "In der Nähe" ein Faden-/Zielkreuz
- "Chat" eine Sprechblase
- Notification-Icon muss auch anders sein

**Comment by androidoma** [comment]
Done
