### ISSUE TITLE
Foto Upload

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#26]
Automatischer Foto upload über die App.

**Comment by tursics** [comment]
Unbedingt. Hierfür müsste auf dem Server ein Script existieren (ich könnte das in PHP schreiben), welches von der App per HTTP-Request gefüttert wird und nichts anderes macht, als eine Mail zu schreiben und zu versenden.

**Comment by pstorch** [comment]
Da gab es noch eine Idee von @hagengraf im Slack:
> Man kann die direkt nach Drupal laden (neuer Node , unpublished)
> Dann eine Notifikation an admin und eine view zum freischalten

**Comment by tursics** [comment]
Das klingt noch einfacher vom Ablauf

**Comment by khgdrn** [comment]
im ersten Schritt wäre es schonmal von Vorteil, wenn die Bilder direkt in ein Shareverzeichnis verschickt würden. 
Die Bilder müssen wir meist eh nochmal anfassen, verpixeln von Gesichtern, Größe anpassen, sollten wir nur dabei bedenken.

**Comment by pstorch** [comment]
Implementiert, siehe #48
