### ISSUE TITLE
Document Firebase setup in README 

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#27]
Steps to copy the https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/java/de/bahnhoefe/deutschlands/bahnhofsfotos/util/FireBaseConstantsTemplate.java class is missing in README

**Comment by androidoma** [comment]
Read.me file was updated with the description of FireBaseConstantsTemplate with the last commit

**Comment by pstorch** [comment]
Thanks @androidoma (also test Slack notification)
