### ISSUE TITLE
URL-Templates in Länderdaten aufnehmen

### ISSUE THREAD

**Issue by pelzvieh** [RailwayStations/RSAndroidApp#30]
Die URL-Templates für Abfahrttafeln sollten in die Länderdaten unter https://railway-stations.org/laenderdaten.json aufgenommen werden, damit die App diese Infos dynamisch mit den Länderdaten auslesen kann. Anschließend sollen die hart kodierten URLs aus der App entfernt werden, entsprechend der todo-Annotationen.

**Comment by pstorch** [comment]
Ist das noch aktuell oder haben wir die Abfahrttafeln raus genommen?

**Comment by pstorch** [comment]
Die API liefert nun auch die Countries mit den URL-Templates für die Abfahrttafeln.

URL: http://api.railway-stations.org/countries
Das Feld `timetableUrlTemplate` kann die folgenden Platzhalter enthalten, die entsprechend der Daten des Bahnhofes ersetzt werden müssen:
- `{title}`
- `{DS100}`

Damit braucht die App keinen Zugriff mehr direkt auf Drupal und kann sich alles über die API holen.
