### ISSUE TITLE
Authentication/nickname very confusing

### ISSUE THREAD

**Issue by ThatOneCalculator** [RailwayStations/RSAndroidApp#345]
There doesn't seem to be a way to make an account or anything? The UI/UX is extremely confusing...

![Screenshot_20221216-125819.png](https://user-images.githubusercontent.com/44733677/208187935-3b708b4c-fb25-4ffd-b21f-9022db77c9f4.png)

**Comment by pstorch** [comment]
You can create an account and login via the "My Data" menu. 
You are right, the flow could be better.

**Comment by ThatOneCalculator** [comment]
It took me like 10 minutes to find "my data"... maybe I'm just dumb but this is the least intuitive app design I've ever seen :skull:

**Comment by pstorch** [comment]
You hold the record now 🤣

Feedback welcome. If you have suggestions on how to improve it.

**Comment by ThatOneCalculator** [comment]
My suggestion would be to adhere much closer to MD3 guidelines. Having standardized places of putting items, menu, nav, profiles, and other elements is always good to have.

**Comment by ThatOneCalculator** [comment]
@pstorch how about something like this? (whipped up in figma)

![image](https://user-images.githubusercontent.com/44733677/208204772-590b9bb9-f3d7-4f38-b188-b4c2222a0857.png)

**Comment by pstorch** [comment]
@ThatOneCalculator that looks really nice. This app is far away from MD3. That would be a huge redesign/rewrite. I don't have the capacity for that right now. But hey, it's open source and PullRequests are more than welcome. If you like.

**Comment by ThatOneCalculator** [comment]
I have 0 clue how to make Android apps 🥴

**Comment by pstorch** [comment]
To improve it a little bit, I implemented an automatic switch to the "My data" screen in case a login is required but missing.
I keep this issue open. Maybe we can improve the login flow further. A complete redesign would be a different topic.

**Comment by pstorch** [comment]
The authorization flow is completely rewritten with #360
