### ISSUE TITLE
Map display doesn't show if stations have photos

### ISSUE THREAD

**Issue by kuro68k** [RailwayStations/RSAndroidApp#347]
![Screenshot_20221219-101020](https://user-images.githubusercontent.com/2674466/208329936-ebe03125-2e56-405a-acd8-3f16ae166837.png)

On the web version, stations without photos are red. It would be very helpful to have this replicated in the app, so I know which ones I need to photograph.

**Comment by pstorch** [comment]
Stations without photos have a red pin:

![Screenshot_20221219_071031_Railway station photos](https://user-images.githubusercontent.com/5598124/208359537-f05f32fc-bc5c-4a7d-ab2e-015344b6928a.jpg)

**Comment by kuro68k** [comment]
My apologies, I had the setting wrong. Thanks.
