### ISSUE TITLE
Map labels are too big

### ISSUE THREAD

**Issue by kuro68k** [RailwayStations/RSAndroidApp#348]
![Screenshot_20221219-101020](https://user-images.githubusercontent.com/2674466/208329996-8b62ce1c-a58a-4cd0-97cb-f6086f4a4ea0.png)

The labels on stations are too large. They make it difficult to see the map and get a sense of where stations are. On the web version the labels are hidden until a station is selected.

**Comment by pstorch** [comment]
You are right, for dense areas the labels use too much space. I'll look at this issue.
