### ISSUE TITLE
Netzlosigkeit darf nicht zum Löschen der DB führen

### ISSUE THREAD

**Issue by khgdrn** [RailwayStations/RSAndroidApp#42]
Habe ich kein Netz und klicke ich auf "Bahnhofsdaten aktualisieren" führt dies zu einem Löschen der Bahnhofsliste.
Das führt dazu, dass die App nicht mehr verwendbar wird, solange ich kein Netz habe.

Dabei könnte man während der Netzlosigkeit durchaus Fotos aufgrund einer veralteten Datenbank schießen und auch später verschicken.

Ich für meinen Teil schätze das als extrem wichtig ein, denn ohne Bahnhofsliste ist die App nicht verwendbar.

**Comment by pstorch** [comment]
Bin dran
