### ISSUE TITLE
Country selection stuck on DE

### ISSUE THREAD

**Issue by HonakerM** [RailwayStations/RSAndroidApp#426]
Hello,

I recently discovered this project so please let me know if this is not the right forum. I have a Samsung s22 running android 13 and the app seems to be stuck on Germany. As you can see in the attached video no matter what I select in the photos menu it stays on DE. 

https://github.com/RailwayStations/RSAndroidApp/assets/37811263/8db583d3-d8ff-409a-a140-881c200c5993

**Comment by pstorch** [comment]
Thanks for reporting. Unfortunately I cannot reproduce. 
What version do yo use? Is it the same behavior when you use the back button from the system menu? Is your internet connection is working? 
What else could it be?

**Comment by HonakerM** [comment]
Hey @pstorch, I'm using version 15.0.2. And good idea, the issue does not happen when I use the system back button. It only occurs when I use the app's button

**Comment by pstorch** [comment]
Thanks @HonakerM, that points me at least into some direction where I can investigate.

**Comment by pstorch** [comment]
I changed the country selection logic and the back navigation. Don't know if it fixes the problem.
@HonakerM would be cool if you could test the next nightly build.

**Comment by HonakerM** [comment]
@pstorch can do! Sorry, I'm still learning the repo but where can I find the nightly build to install?

**Comment by pstorch** [comment]
You can download the apk of the nightly build manually from here: https://fdroid.storchp.de/fdroid/repo/ or add my fdroid repo to your fdroid client (if you use fdroid) and download it from there.

**Comment by HonakerM** [comment]
@pstorch that resolved the issue! I'm able to use either the menu button or system button to save my selection.

**Comment by pstorch** [comment]
Thanks for the quick test. Then I can prepare a Bugfix release at the weekend. 

Regarding issues for new contributors: currently there aren't any. The remaining issues listed in this repo are quite old and probably not  relevant anymore. We need to clean them up. Little bugs I try to fix right away.
But I can leave some for you now. 😉

On the long term I want to improve the codebase in general. Some ideas:
- add more unit tests (coverage is poor)
- introduce ViewModel
- Use Room as persistence layer
- use jetpack compose

But these are rather big changes. I don't know where your expertise is.

Do you have any ideas?
