### ISSUE TITLE
Map doesn't remember last position 

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#427]
Reported via email:

> Hi there. I think it used to be the case that the app would open relatively where I last closed it, i.e. even though the app opens at the list of the stations, the general map area was being kept when I switched to the map screen.
> Now the map always opens in the middle of Siberia for some reason, which is super annoying, since I have to move it back to Europe every time. If anything can be done about it in future versions, what'll be fantastic!

**Comment by pstorch** [comment]
@HonakerM something for you?

**Comment by HonakerM** [comment]
@pstorch sure! I'll try to get to this one when I have time

**Comment by pstorch** [comment]
@HonakerM I would like to have it fixed this weekend. If you don't have time, no worries. I can take over. Sorry, I don't want to put pressure on you. We'll find other "first issues".

**Comment by pstorch** [comment]
@HonakerM I've updated the issues in this repo. Have a look and if there is something interesting for you, feel free to comment on it and start. There are no pressing bugs right now :wink:
