### ISSUE TITLE
Back Stack nicht korrekt nach Chat

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#60]
Öffnet man den Chat über die Notification beendet sich die App, wenn man auf zurück geht.
Hier sollte sich die Hauptseite öffnen.

**Comment by pelzvieh** [comment]
Meiner bescheidenen Ansicht nach könnte das daran liegen, dass android:parentActivityName nicht die Abkürzung ".MyName" unterstützt, die android:name anbietet.

**Comment by pstorch** [comment]
Leider nicht, habs ausprobiert. Ich glaube das liegt daran, dass es keinen Backstack gibt. Die Chat Activity wird ja aus der Notification heraus aufgerufen. Da muss man irgendwie den Backstack selbst bauen.

https://developer.android.com/training/implementing-navigation/temporal.html#SynthesizeBackStack

Ein ähnliches Problem gibt es mit der MyDataActivity, wenn sie aus der Mail heraus gestartet wurde. Da gibt es dann auch keinen Backstack.

**Comment by pstorch** [comment]
obsolete
