### ISSUE TITLE
Handle disabled location services

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#74]
Some users have disabled their location services (GPS off). The MapsActivity needs to handle this situation. At the moment it moves the map to the Zero Coordinates somewhere in the ozean.

The MapsActivity should query the location settings like described here: https://developer.android.com/training/location/change-location-settings.html.
A fallback could calculate the center of all the map markers. We cannot hardcode a single position (as before) because we support several countries.

**Comment by stefanopitz** [comment]
Easy solutions for now: center somewhere in Europe instead at 0,0 -- saves some scrolling effort for every country. 

Second solution: Preferences field to set a custom default

**Comment by pstorch** [comment]
Japan is coming sooner or later, too. 😉

**Comment by pstorch** [comment]
Implemented a simple solution to calculate the center of all the map markers.
