### ISSUE TITLE
Add link to the local railway apps into the detailsview

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#82]
There could be a link to the local railway app of the current country into the google playstore.

**Comment by kaiwinter** [comment]
Do we know the local railway operator by the current data model? There may be more than one at a station...

**Comment by pstorch** [comment]
It's not part of our API. @androidoma what was your idea here?

**Comment by pstorch** [comment]
We want to put the Links to the Apps into the Countrydata of the API. Then we could add the Link in the menu of the Details activity.

**Comment by pstorch** [comment]
Depending on https://github.com/RailwayStations/RSAPI/issues/32

**Comment by pstorch** [comment]
The API endpoint http://api.railway-stations.org/countries knows to new fields per country: `providerAndroidApp` and `providerIosApp`.
We don't have all provider apps for all countries configured, but for `de`, `ch`, `at`, `fr` and `pl`.

If the `providerAndroidApp` is not `null`, a menu entry with this link should be added on the details page.

**Comment by kaiwinter** [comment]
I'm working on this...

**Comment by kaiwinter** [comment]
I will use this icon in the toolbar: https://material.io/resources/icons/?icon=launch&style=baseline
What confuses me a bit is that there are multiple icon resources, for instance:
- `ic_directions_white_24dp` (4 PNGs in different dpi folders) - used in `NearbyBahnhofNotificationManager`
- `ic_directions_white_36dp` (4 PNGs in different dpi folders) - no usages
- `ic_directions_white_24px` (1 XML) - used in `details.xml`

So I will just add `ic_launch_white_24px.xml` and no PNGs.
