### ISSUE TITLE
Translation into Finnish 

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#83]
The App has the possiblity to select different countries for railway stations. To make it better to use for local users we need a translation in Finnish. The translation is necessary for this [file](https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/res/values/strings.xml)

**Comment by pstorch** [comment]
Please help via: https://crowdin.com/project/rsandroidapp

**Comment by khgdrn** [comment]
Was ist mit Hannu?

**Comment by pstorch** [comment]
If someone wants to contribute during `hacktoberfest`, please leave a comment here and I'll assign this issue to you.

**Comment by mondlicht-und-sterne** [comment]
https://crowdin.com/project/railwaystationsandroidapp/fi

89 % have i translated last days ;)

**Comment by pstorch** [comment]
Ha, I completely forgot about this issue. So we can nearly close it, thanks to your help

**Comment by pstorch** [comment]
Translations now done via crowdin, closing here
