### ISSUE TITLE
Translation into Spanish

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#84]
The App has the possiblity to select different countries for railway stations. To make it better to use for local users we need a translation into Spanish. The translation is necessary for this [file](https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/res/values/strings.xml)

**Comment by pstorch** [comment]
Please help via: https://crowdin.com/project/rsandroidapp

**Comment by khgdrn** [comment]
Hier könnten wir Vanessa fragen, spanischesprechende Kollegin. Allerdings braucht man für cowdin einen Login.

**Comment by pstorch** [comment]
Crowdin haben wir doch wieder rausgeschmissen, da es mehr verwirrt hat und bisher eh kein externer beim Übersetzen geholfen hat.

**Comment by pstorch** [comment]
If someone wants to contribute during `hacktoberfest`, please leave a comment here and I'll assign this issue to you.

**Comment by troyodk** [comment]
I can translate it to spanish

**Comment by pstorch** [comment]
@troyodk you are welcome

**Comment by pstorch** [comment]
fixed by #107
