### ISSUE TITLE
Translation into French

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#85]
The App has the possiblity to select different countries for railway stations. To make it better to use for local users we need a translation into French. The translation is necessary for this [file](https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/res/values/strings.xml)

**Comment by pstorch** [comment]
Please help via: https://crowdin.com/project/rsandroidapp

**Comment by khgdrn** [comment]
ich könnte hier Christophe fragen, Franzose in meinem Team

**Comment by pstorch** [comment]
If someone wants to contribute during `hacktoberfest`, please leave a comment here and I'll assign this issue to you.

**Comment by rakvium** [comment]
@pstorch, I think that @deatheguard and me can deal with it.
Should we also include `report_ghost_station` and `remove_station` from #106?

**Comment by pstorch** [comment]
@rakvium OK, I'll assign it to you. The other issue is already taken.

**Comment by pstorch** [comment]
@rakvium just realized I cannot assign it to outside collaborators. I've assigned it to me as a stand in, to indicate it is taken. Looking forward to your pull request.

**Comment by deatheguard** [comment]
@pstorch I've started translating English into French but I had to stop at the line 35 because I need know exactly what do you mean by "Own Web page". Is it "Your web page"? Or "Have a web page" as a suggestion?

**Comment by pstorch** [comment]
@deatheguard it's "Your web page". A user can have links from the photos to either one of several social media profiles or to his/her  own web page. 
Does my explanation make sense?

**Comment by deatheguard** [comment]
@pstorch yes, quite. Thank you.

**Comment by pstorch** [comment]
fixed by @rakvium and @deatheguard, many thanks
