### ISSUE TITLE
Translation into Polish

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#86]
The App has the possiblity to select different countries for railway stations. To make it better to use for local users we need a translation into Polish. The translation is necessary for this [file](https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/res/values/strings.xml)

**Comment by pstorch** [comment]
Please help via: https://crowdin.com/project/rsandroidapp

**Comment by pstorch** [comment]
If someone wants to contribute during `hacktoberfest`, please leave a comment here and I'll assign this issue to you.

**Comment by pstorch** [comment]
Translation to polish started via #108. Still something left. If someone wants to contribute, you're welcome.

**Comment by kazigk** [comment]
I will do it! Please give me a few days, because I'm already working on another issue

**Comment by pstorch** [comment]
@kazigk you are welcome

**Comment by pstorch** [comment]
Done via Crowdin
