### ISSUE TITLE
Translation into English

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#87]
The App has the possiblity to select different countries for railway stations. To make it better to use for local users we need a translation into English. The translation is necessary for this [file](https://github.com/RailwayStations/RSAndroidApp/blob/master/app/src/main/res/values/strings.xml)

**Comment by pstorch** [comment]
A first version of an english translation is done. Proofreading would be nice https://crowdin.com/project/rsandroidapp/en#
