### ISSUE TITLE
Lizenzen unter Fotos hinzufügen

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#88]
Die Fotos brauchen noch die Lizenz mit Link zum Lizenztext.

**Comment by pstorch** [comment]
Der Lizenztext ist mittlerweile da, fehlen noch die entsprechenden Links.

**Comment by androidoma** [comment]
https://creativecommons.org/publicdomain/zero/1.0/deed.de

https://creativecommons.org/licenses/by-sa/4.0/

**Comment by kaiwinter** [comment]
Falls noch niemand daran arbeitet, kann ich die Links einbauen. Man bekommt es auch so hin, dass je nach Systemsprache die richtige Sprache der Lizenz aufgerufen wird.

**Comment by pstorch** [comment]
Das wäre super, gerne kannst du daran arbeiten.

**Comment by pstorch** [comment]
Maybe wait for RailwayStations/RSAPI#26

**Comment by pstorch** [comment]
API is extended to provide the `licenseUrl` attribute, so this can be implemented now.

**Comment by kaiwinter** [comment]
I pushed a suggestion how this could be implemented. If the user clicks the

**Comment by kaiwinter** [comment]
This is a suggestion how opening the license URL could work. If the user taps the photographer/license tagline a Dialog pops up where the user can choose if the photographer website or the license website should be open. The item in the Dialog is only active if an URL is available.

**Comment by pstorch** [comment]
fixed by #111
