### ISSUE TITLE
Einbindung Fahrstühle

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#90]
Die Fahrstuhldaten sind in ElasticSearch und können von dort abgegriffen werden. Datensatz der Deutschen Bahn.
Benötigt wird:
1. Kennzeichen im Ländersatz, ob Fahrstuhldaten vorhanden sind
2. Import der deutschen Fahrstuhldaten
3. Unter Einstellungen sollen die Maße von Fahrrad und/oder Rollstuhl eingetragen werden können
4. Ausgabe der Fahrstuhldaten zu dem aktuellen Bahnhof (DetailsActivity) als extra Menüpunkt in Tabelle
5. Herunterladen der Fahrstuhldaten mit den Länderdaten, damit offline verfügbar
6. Online Fahrstuhlstatus aus FaSta abfragen 
7. Berechnung, ob das Fahrrad / der Rollstuhl in den Aufzug passt anhand Kabinentiefe und Kabinentür und der Daten aus den Einstellungen - siehe Punkt 1.

**Comment by pstorch** [comment]
Wird mittlerweile von der Bahnhof Live App angeboten
