### ISSUE TITLE
Eliminierung der Auswahl der CC40

### ISSUE THREAD

**Issue by khgdrn** [RailwayStations/RSAndroidApp#98]
CC40 nicht mehr auswählbar anbieten. Für bestehende Fotografen kann das gerne weiterhin angezeigt werden. Darf aber maximal nur auf CC0 geändert werden. Kleiner Hinweistext, warum das nicht auswählbar sein soll ist für den User hilfreich.

**Comment by pstorch** [comment]
Da müssten wir bei Neuregistrierung von bestehenden Usern im Backend eine Abfrage machen, ob es den schon gibt und welche Lizenz bisher eingestellt war. Der Nickname wird aber erst weiter unten eingetragen. Da müssen wir mal den Dialog überdenken.

**Comment by khgdrn** [comment]
ok, aber es ist doch eh nen Trugschluss zu denken, dass man heute jedes mal was einstellen könne wie man möchte. Was einmal angelegt ist, wird nicht geändert, solange Gaby das nicht sagt. Aber, es macht doch wirklich gar keinen Sinn mehr, dass jetzt jemand cc40 einstellt, es werden 5 oder 6 Fotos hochgeladen, Gaby klärt das über DM und wir passen wieder alles an, weil wir kein CC40 mehr wollen. Dann sollten wir es doch gleich deaktivieren und unsere Bestandsfotografen lassen sich entweder auch überzeugen oder sie bleiben unangetastet, auch wenn sie mal die App neu installieren. Ich finde es einfach nicht angemessen genug, dass wir die Auswahl drin lassen, um die 10 Leute zu "beruhigen". Was wir auch machen können, ich lege einfach niemanden mit CC40 an, egal was auswählt wurde.

**Comment by pstorch** [comment]
Ja, guter Punkt.
Lass uns CC0 als Checkbox implementieren, die bei der Registrierung abgehakt werden muss. Falls sich dann einer der wenigen User mit CC4 neu anmeldet und es partout nicht möchte, können wir ihm ja sagen, dass wir es im Hintergrund für ihn auf CC4 belassen. Oder besser es zählt dann halt CC0 automatisch für alle neuen Fotos ;) (warum sollten wir neue Fotos noch mit CC4 akzeptieren, wenn wir das bei neuen Fotografen auch nicht tun?).
